server:
  port: 8761
eureka:
  instance: 
    preferIpAddress: true
    hostname: localhost
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 30000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
